### ISSUE TITLE
Data Request: term dates in `/terms/list` endpoint

### ISSUE THREAD

**Issue by Uberi** [uWaterloo/api-documentation#101]
Currently, the [terms list endpoint](https://github.com/uWaterloo/api-documentation/blob/master/v2/terms/list.md) contains term IDs and names. The proposed change is to also add official term dates, as per pages like [those published by SAFA](https://uwaterloo.ca/student-awards-financial-aid/2016-2017-official-term-dates-osap).

A potential new format for the response:

```json
{
  "meta":{
    ...
  },
  "data":{
    "current_term":1139,
    "previous_term":1135,
    "next_term":1141,
    "listings":{
      ...
      "2017":[
        {
          "id":1171,
          "name":"Winter 2017",
          "start":"2017-01-03", <- ADDED
          "end":"2017-04-25" <- ADDED
        },
        ...
      ]
    }
  }
}
```

This would make it easier to, for example, show calendar ranges when calculating schedule bounds. My personal use case would be to make [COURSERATOR3000](http://courserator.anthony-zhang.me/) automatically update for each term as data becomes available.

**Comment by KartikTalwar** [comment]
Hey @Uberi, I can let @zachomedia comment on the endpoint that lets you query the official dates for a term as an endpoint (currently being worked on), but we added a temporary solution to this a while back (which hasn't been kept up-to-date unfortunately).

From your commit, looks like the start and end dates manually added by you, if you want to submit a pull request that modifies this csv below, you should be able to access the data from the term_id endpoint.

https://github.com/uWaterloo/Datasets/blob/master/Terms/dates.csv 

https://api.uwaterloo.ca/v2/terms/1145.json

**Comment by zachomedia** [comment]
There is an endpoint to get all the important dates for a term (https://api.uwaterloo.ca/v2/terms/1175/importantdates.json?key=[your-api-key]).

We are currently working on documentation for the endpoint, but the endpoint is available for use.

**Comment by Uberi** [comment]
I noticed that this was recently documented in 28a5cc6a7cea86e6eeb9037d3b60be7501b7b219, so term dates are now [retrievable programmatically](https://github.com/Uberi/COURSERATOR3000/blob/d6b0674735e223fe1261f390b51b71f7ec190303/COURSERATOR3000/course_info.py#L30).

Thanks for adding those in!
