### ISSUE TITLE
javaAPI HTTP response code: 501 for term/enrollement

### ISSUE THREAD

**Issue by tingwei758** [uWaterloo/api-documentation#106]
JavaAPI : TermsAPI.class

error:
Server returned HTTP response code: 501 for URL: https://api.uwaterloo.ca/v2/term/1179/MATH/enrollment.json

I guess there is a missing s in JavaAPI.class, constant TERM_SUBJECT_CATALOG_SCHEDULE, line 19

**Comment by zachomedia** [comment]
Hello @tingwei758,

Unfortunately, the University of Waterloo Open Data project does not support the third-party libraries. Please reach out to the developer of the library you are using.
