### ISSUE TITLE
Unable to request API key

### ISSUE THREAD

**Issue by teb951999** [uWaterloo/api-documentation#109]
Unable to request API key. Clicking the link on page redirects to GitHub.

**Comment by sbobkin** [comment]
Hi teb. 
This was done on purpose as we do not want significant projects to begin on the existing API endpoints with the transition messaging we've released. Can you let me know what you were hoping to do with the API and we can likely work something out in the interim?

**Comment by teb951999** [comment]
Hey, thanks for the response. We're looking at building a Reddit bot that will query the uwaterloo API for course info and suggest courses, schedule, find exam timings, etc.

**Comment by smusali** [comment]
Hey @sbobkin , can you respond to @teb951999 's request? Thanks!

**Comment by sbobkin** [comment]
Hey @smusali and @teb951999 sorry didn't get a notification for the follow up response. While we've hidden the link and don't intend to make new signs up widely available, it's still possible to get a key at https://uwaterloo.ca/api/register
