### ISSUE TITLE
No data returned in historical wifi usage endpoint

### ISSUE THREAD

**Issue by arora-aditya** [uWaterloo/api-documentation#112]
Querying the **wireless/historical** endpoint never returns data:
Example:
`GET https://api.uwaterloo.ca/v2/wireless/historical/usage.json?from=2017-06-28T160000-0400&to=2017-06-28T161500-0400&key=REMOVED_FOR_SECURITY`
returns
`{"meta":{"requests":4,"timestamp":1527458511,"status":204,"message":"No data returned","method_id":10005,"method":{}},"data":[]}`

Similarly:
`GET https://api.uwaterloo.ca/v2/wireless/historical/clients.json?from=2017-07-18T160000-0400&to=2017-07-19T235959-0400&key=REMOVED_FOR_SECURITY`
returns
`{"meta":{"requests":4,"timestamp":1527458420,"status":204,"message":"No data returned","method_id":10007,"method":{}},"data":[]}`

All the endpoints under wireless/historical are not returning any data, is there a fix for this?

**Comment by arora-aditya** [comment]
Any update on this?

**Comment by sbobkin** [comment]
Sorry for the late reply, we've publicized that we're only going to address critical issues in the existing version. That remains true due to the stack it's running and our currently available staff resources. At this time this will not be addressed.
