### ISSUE TITLE
Endpoints for Warriors Open Rec Hours?

### ISSUE THREAD

**Issue by yzgyyang** [uWaterloo/api-documentation#113]
Just wondering if it's feasible to implement an API endpoint for Warrior open recreation hours. Currently the data is at https://athletics.uwaterloo.ca/sports/2010/7/21/Open_Recreation_and_Swim_Times.aspx.

**Comment by sbobkin** [comment]
We can consider it in the vNext we're working on now. I believe Portal currently gets that data through an API, I'll have to talk to them.

**Comment by yzgyyang** [comment]
Cool, let me know if I can be a help! ;)

**Comment by sbobkin** [comment]
Going to close this issue here, it's noted internally. I want to get issues down to one of the projects here, and going to use the Datasets and OpenData ones.
