### ISSUE TITLE
Event Site Slug

### ISSUE THREAD

**Issue by weienwong** [uWaterloo/api-documentation#58]
Hey guys,

First off, love the work you guys are doing, your API is helping me a lot with my app (http://watsup.herokuapp.com/)

That being said, I noticed that event site slugs (from resources/sites) that contain the "/" does not return the proper data. How would I use a site slug that contains the "/" character. 

Here's an example (I left the API key intentionally):

![screenshot from 2015-05-08 21 01 32](https://cloud.githubusercontent.com/assets/1614781/7547926/793cf58a-f5c5-11e4-9557-7989695c8c04.png)

Thanks guys!

**Comment by RobinsonMann** [comment]
I suspect that URL encoding the the site_name would give the correct result, however I have no way of confirm if this is true or not as if you go to a site_name that doesn't correspond to a site you are simply told that their isn't any data, and not that it is an unused site_name.

So, does anyone know of any site names that contain '/' (Or also ' ') that actually does have some events?

**Comment by weienwong** [comment]
as i have shown in the image the slug "library/news" contains the "/" character. According to the events listing API, there are events under the library/news.

**Comment by KartikTalwar** [comment]
Hey @weienwong thanks for catching that, interestingly the site's name does contain `/`. We'll try to get this resolved hopefully tomorrow

**Comment by weienwong** [comment]
No problem! Once again, I really like this project and I hope you guys keep up the good work!

**Comment by iaMeteor** [comment]
Has this issue been solved yet?

**Comment by KartikTalwar** [comment]
@weienwong this error has now been fixed. Sorry for the delay

**Comment by weienwong** [comment]
Awesome! Thanks Kartik!
