### ISSUE TITLE
Greyhound Information and Example Incorrect

### ISSUE THREAD

**Issue by ArkaZeen** [uWaterloo/api-documentation#90]
The readme under the Greyhound information actually displays construction information.

I thought you would like to know :)

**Comment by RobinsonMann** [comment]
Thanks for finding this. 

Closing this issue as Kelvin Wu fixed it in `[f7190f9](https://github.com/hkwu/api-documentation/commit/f7190f9b3d22401b15bf249292897ebef5fab9e3)`.
