### ISSUE TITLE
python api missing GET /terms/{}/courses'

### ISSUE THREAD

**Issue by steverweber** [uWaterloo/api-documentation#94]
this is not an issue with the documents but an issue with the python module uwaterlooapi

missing term_courses

temp workaround.
```
from uwaterlooapi import UWaterlooAPI, UWaterlooAPIFunction

from shad import BaseAPI, APIFunction, get_bind
class UWaterlooAPIfix(UWaterlooAPI):
    pass
bind = get_bind(UWaterlooAPIfix)
@bind
class term_courses(UWaterlooAPIFunction):
    path = '/terms/{}/courses'
```

**Comment by KartikTalwar** [comment]
Hi @steverweber since the wrappers are independent contributions of the developers using the API, you can try submitting a pull request to @amjoconn's repo on bitbucket!

**Comment by albertoconnor** [comment]
Hi @steverweber, you ar definitely correct, I haven't had too much time to maintain the library, but I welcome pull requests!

If you prefer I can migrate the existing code base to github

**Comment by steverweber** [comment]
yes github is preferred.

**Comment by albertoconnor** [comment]
https://github.com/albertoconnor/uwaterlooapi

I brought over shad as well... https://github.com/albertoconnor/shad

@steverweber I can update pypi, if you have PR we can make the improvement available to everyone.

**Comment by steverweber** [comment]
honestly i think this python code is a little overkill... personally I'd just use /requests/ directly.

anyways I'll fork and push the small change.

**Comment by albertoconnor** [comment]
@steverweber nothing is stopping you from doing that, or making a thinner wrapper if you prefer. I wrote it awhile ago and it might have been a bit too ambitious :)

**Comment by steverweber** [comment]
nevertheless shad looks badass :)

**Comment by albertoconnor** [comment]
I have updated uwaterlooapi on pypi:

https://pypi.python.org/pypi/uwaterlooapi/0.3.1
